#%RAML 1.0
title: helloworld
/flights:
    get:
        responses:
            200:
              body:
                application/json:
                  example:
                    {"message" : "Hello"}

    post:
        responses:
            201:
              body:
                application/json:
                  example:
                    {"message" : "HelloWorld!"}

